stages:
  - build
  - test

build:
  stage: build
  script:
  - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/build.sh bluetab/amazonlinux-phoenix-postgresql-redis:20180525133152
  artifacts:
    untracked: true

test:
  stage: test
  script:
  - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/test.sh bluetab/amazonlinux-phoenix-postgresql-redis:20180525133152
  artifacts:
    untracked: true
